### ISSUE TITLE
Support for `half`

### ISSUE THREAD

**Issue by codekansas** [harvardnlp/genbmm#3]
Hi! I believe this implementation can be easily extended to support half-precision by replacing

```
AT_DISPATCH_FLOATING_TYPES
```

with

```
AT_DISPATCH_FLOATING_TYPES_AND_HALF
```

**Comment by srush** [comment]
Thanks! Will do. 

(there are a bunch of other optimizations I have been meaning to add to this library. Hope to get back to it soon. )

**Comment by srush** [comment]
This got checked in finally.
